stages:
  
  Training:
    cmd: python fraud_svm.py
    
    deps:
      - fraud_svm.py
      - Data/creditcard.csv
      

    outs:
      - Models/Fraud_SVM.pkl
      - Data/x_test.csv
      - Data/y_test.csv
    

   
  Testing:
    cmd: python fraud_svm_test.py 

    deps:
      - fraud_svm_test.py 
      - Data/x_test.csv
      - Data/y_test.csv
      - Models/Fraud_SVM.pkl
      
    outs:
      - auc.png
      - confusion_mat.png
    

    metrics:   

      - Output/Accuracy.json:
          cache: false

  



    plots:    

      - plots.json:
          cache: false
          x: fpr
          y: tpr          




